name: Build & Deploy
on:
  push:
    branches: [main]
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: LAMP Deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.SSH_HOST}} # server ip
          key: ${{secrets.SSH_KEY}} 
          username: ${{secrets.SSH_USERNAME}} #server user
          
          script: |
            cd /var/www/html
            git pull
            echo 'Deployment successful to digital ocean'
          
